server.port: 8080
server.servlet.contextPath: /DynamoDBExample

application.connectivity.dynamodb.local.port: 9090

application.connectivity.dynamodb.service.endpoint: http://localhost:9090
application.connectivity.dynamodb.signin.region: us-west-2
application.connectivity.dynamodb.awsAccessKeyId: dummy
application.connectivity.dynamodb.awsSecretKey: dummy

sqlite4java.library.path: ${basedir}/target/dependencies