spring.main.allow-bean-definition-overriding: false

server.port: 8080
server.servlet.contextPath: /DynamoDBExample

application.connectivity.dynamodb.service.endpoint: http://localhost:9090
application.connectivity.dynamodb.signin.region: us-west-2
application.connectivity.dynamodb.awsAccessKeyId: no-op-access-key-id
application.connectivity.dynamodb.awsSecretKey: no-op-secret-key