package com.taranovski.example.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.taranovski.example.dynamodb.domain.converter.DynamoDbLocalDateConverter;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Created by Alyx on 09.02.2020.
 */
@DynamoDBTable(tableName = Person.TABLE_NAME)
public class Person {
    public static final String TABLE_NAME = "Persons";

    public static final String ID = "Id";

    public static final String NAME = "Name";
    public static final String HOURS_PER_WEEK = "HoursPerWeek";
    public static final String SALARY = "Salary";
    public static final String DATE_OF_BIRTH = "DateOfBirth";

    private String id;
    private String name;
    private int hoursPerWeek;
    private BigDecimal salary;
    private LocalDate dateOfBirth;

    @DynamoDBHashKey(attributeName = ID)
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName= NAME)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName= HOURS_PER_WEEK)
    public int getHoursPerWeek() {
        return hoursPerWeek;
    }

    public void setHoursPerWeek(int hoursPerWeek) {
        this.hoursPerWeek = hoursPerWeek;
    }

    @DynamoDBAttribute(attributeName= SALARY)
    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    @DynamoDBAttribute(attributeName= DATE_OF_BIRTH)
    @DynamoDBTypeConverted(converter = DynamoDbLocalDateConverter.class)
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", hoursPerWeek=" + hoursPerWeek +
                ", salary=" + salary +
                ", dateOfBirth=" + dateOfBirth +
                '}';
    }
}
